# Generated by Django 4.1.7 on 2023-03-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_updated_at_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
    ]
